### ISSUE TITLE
feat : 습격 문제 category filter 기능

### ISSUE THREAD

**Issue by JerryK026** [team-Interviewers/team-Interviewers-FE#14]
## 이 이슈가 해결되어야 하는 이유
사용자에 따라 관심 없는 주제에 대해서는 문제를 거를 수 있어야 합니다.

## 요구사항
```mermaid
flowchart TD
    A[사용자가 설정 버튼을 클릭한다] --> B[설정창이 팝업된다]
    B --> C[설정 창에 `운영체제, 네트워크, 데이터베이스, 자료구조, Java, Js, 브라우저, 기타` 항목들이 각 체크박스와 함께 등장한다]
    C --> D[사용자 입장에서 체크된 항목에 해당되는 주제에 대한 면접 질문만 노출된다]
```

## 와이어프레임

![Image](https://github.com/team-Interviewers/team-Interviewers-FE/assets/55067949/67f86a79-74d0-4138-89bc-49c6dc9b28f0)

**Comment by pengooseDev** [comment]
## 설명
- popup의 state를 DOM과 synchronize하여 question.json의 문제 중 조건에 맞는 문제만 렌더링한다.

## 기능명세
- [x] popup 컴포넌트 스타일링.
- [ ] 문제 타입 렌더링(json 데이터 받아와서 동적으로 렌더링해도 좋을듯).
- [ ] content script에서 문제의 조건을 핸들링하는 커스텀 훅 구현.
- [ ] popup의 state가 변할 때, 커스텀 훅을 조작하여 문제 조건부 렌더링.

미션 호딱 끝내고 금요일 전 까지 마무리해보겠습니다 :) Notion Ticket 생성 및 할당해두었습니다.

**Comment by pengooseDev** [comment]
https://github.com/team-Interviewers/team-Interviewers-FE/pull/15
